### ISSUE TITLE
의견 목록 불러오기 기능 에러

### ISSUE THREAD

**Issue by TypingOK** [Cocktail-Masters/Banana-Vote-BE#166]
의견 목록을 불러오는 기능에 문제가 발생했구요
의견이 0개면 잘 불러와지는데 1개 이상 달리면 바로 에러 납니다.

```
2023-06-15T06:43:25.654Z  WARN 1 --- [nio-8080-exec-9] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: S1009
2023-06-15 15:43:25 2023-06-15T06:43:25.654Z ERROR 1 --- [nio-8080-exec-9] o.h.engine.jdbc.spi.SqlExceptionHelper   : Statement.executeQuery() cannot issue statements that do not produce result sets.
2023-06-15 15:43:25 org.springframework.orm.jpa.JpaSystemException: JDBC exception executing SQL [countOpinionsQuery]
2023-06-15 15:43:25     at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:321)
2023-06-15 15:43:25     at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
2023-06-15 15:43:25     at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
2023-06-15 15:43:25     at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
2023-06-15 15:43:25     at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
2023-06-15 15:43:25     at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2023-06-15 15:43:25     at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:134)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2023-06-15 15:43:25     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2023-06-15 15:43:25     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
2023-06-15 15:43:25     at jdk.proxy2/jdk.proxy2.$Proxy167.findOpinionsByVoteIdAndOption(Unknown Source)
2023-06-15 15:43:25     at com.cocktailmasters.backend.vote.service.OpinionService.findOpinions(OpinionService.java:52)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-15 15:43:25     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-06-15 15:43:25     at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2023-06-15 15:43:25     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
2023-06-15 15:43:25     at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
2023-06-15 15:43:25     at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:390)
2023-06-15 15:43:25     at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2023-06-15 15:43:25     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
2023-06-15 15:43:25     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
2023-06-15 15:43:25     at com.cocktailmasters.backend.vote.service.OpinionService$$SpringCGLIB$$0.findOpinions(<generated>)
2023-06-15 15:43:25     at com.cocktailmasters.backend.vote.controller.OpinionController.findOpinions(OpinionController.java:56)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-15 15:43:25     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-06-15 15:43:25     at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
2023-06-15 15:43:25     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
2023-06-15 15:43:25     at com.cocktailmasters.backend.vote.controller.OpinionController$$SpringCGLIB$$0.findOpinions(<generated>)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-06-15 15:43:25     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-15 15:43:25     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-06-15 15:43:25     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
2023-06-15 15:43:25     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
2023-06-15 15:43:25     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
2023-06-15 15:43:25     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
2023-06-15 15:43:25     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
2023-06-15 15:43:25     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
2023-06-15 15:43:25     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
2023-06-15 15:43:25     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
2023-06-15 15:43:25     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
2023-06-15 15:43:25     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
2023-06-15 15:43:25     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705)
2023-06-15 15:43:25     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
2023-06-15 15:43:25     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
2023-06-15 15:43:25     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117)
2023-06-15 15:43:25     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
2023-06-15 15:43:25     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
2023-06-15 15:43:25     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter.doFilterInternal(DefaultLogoutPageGeneratingFilter.java:58)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:188)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:174)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:181)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
2023-06-15 15:43:25     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at com.cocktailmasters.backend.account.jwt.filter.JwtAuthenticationProcessingFilter.checkAccessTokenAndAuthentication(JwtAuthenticationProcessingFilter.java:93)
2023-06-15 15:43:25     at com.cocktailmasters.backend.account.jwt.filter.JwtAuthenticationProcessingFilter.doFilterInternal(JwtAuthenticationProcessingFilter.java:55)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
2023-06-15 15:43:25     at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
2023-06-15 15:43:25     at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
2023-06-15 15:43:25     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
2023-06-15 15:43:25     at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
2023-06-15 15:43:25     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2023-06-15 15:43:25     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
2023-06-15 15:43:25     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
2023-06-15 15:43:25     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
2023-06-15 15:43:25     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2023-06-15 15:43:25     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
2023-06-15 15:43:25     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
2023-06-15 15:43:25     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2023-06-15 15:43:25     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2023-06-15 15:43:25     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
2023-06-15 15:43:25     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
2023-06-15 15:43:25     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2023-06-15 15:43:25     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
2023-06-15 15:43:25     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
2023-06-15 15:43:25     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
2023-06-15 15:43:25     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2023-06-15 15:43:25     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2023-06-15 15:43:25     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2023-06-15 15:43:25     at java.base/java.lang.Thread.run(Thread.java:833)
2023-06-15 15:43:25 Caused by: org.hibernate.exception.GenericJDBCException: JDBC exception executing SQL [countOpinionsQuery]
2023-06-15 15:43:25     at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:61)
2023-06-15 15:43:25     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
2023-06-15 15:43:25     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
2023-06-15 15:43:25     at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:253)
2023-06-15 15:43:25     at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:146)
2023-06-15 15:43:25     at org.hibernate.sql.results.jdbc.internal.AbstractResultSetAccess.getMetaData(AbstractResultSetAccess.java:33)
2023-06-15 15:43:25     at org.hibernate.sql.results.jdbc.internal.AbstractResultSetAccess.getColumnCount(AbstractResultSetAccess.java:49)
2023-06-15 15:43:25     at org.hibernate.query.results.ResultSetMappingImpl.resolve(ResultSetMappingImpl.java:187)
2023-06-15 15:43:25     at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.resolveJdbcValuesSource(JdbcSelectExecutorStandardImpl.java:559)
2023-06-15 15:43:25     at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:350)
2023-06-15 15:43:25     at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)
2023-06-15 15:43:25     at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)
2023-06-15 15:43:25     at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
2023-06-15 15:43:25     at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:105)
2023-06-15 15:43:25     at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:602)
2023-06-15 15:43:25     at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)
2023-06-15 15:43:25     at org.hibernate.query.Query.getResultList(Query.java:94)
2023-06-15 15:43:25     at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.count(JpaQueryExecution.java:180)
2023-06-15 15:43:25     at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.lambda$doExecute$0(JpaQueryExecution.java:175)
2023-06-15 15:43:25     at org.springframework.data.support.PageableExecutionUtils.getPage(PageableExecutionUtils.java:63)
2023-06-15 15:43:25     at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:174)
2023-06-15 15:43:25     at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90)
2023-06-15 15:43:25     at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148)
2023-06-15 15:43:25     at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136)
2023-06-15 15:43:25     at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
2023-06-15 15:43:25     at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
2023-06-15 15:43:25     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
2023-06-15 15:43:25     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2023-06-15 15:43:25     at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2023-06-15 15:43:25     at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
2023-06-15 15:43:25     at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:390)
2023-06-15 15:43:25     at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
2023-06-15 15:43:25     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2023-06-15 15:43:25     at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
2023-06-15 15:43:25     ... 152 more
2023-06-15 15:43:25 Caused by: java.sql.SQLException: Statement.executeQuery() cannot issue statements that do not produce result sets.
2023-06-15 15:43:25     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
2023-06-15 15:43:25     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
2023-06-15 15:43:25     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
2023-06-15 15:43:25     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
2023-06-15 15:43:25     at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:928)
2023-06-15 15:43:25     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
2023-06-15 15:43:25     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
2023-06-15 15:43:25     at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:217)
2023-06-15 15:43:25     ... 184 more
```

**Comment by swoody1101** [comment]
추가로 tag 상위 10 불러오기 수정
